services:
  flask:
    build: file_service
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SERVICE_DIRECTORY=/app/static
    ports:
      - "9000:5000"
    volumes:
      - /mnt/ceph/media/factorio/linux-script-output/chunk-screenshots:/app/static:ro
      - ./file_service:/app

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"