services:
  flask:
    build: file_service
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SERVICE_DIRECTORY=/app/static
    ports:
      - "9000:5000"
    volumes:
      - /mnt/ceph/media/factorio/linux-script-output:/app/static:ro
      - ./file_service:/app

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8123:80"
    depends_on:
      - flask